### PR TITLE
An anti-spam extension

### PR DESCRIPTION
**Pull request by picman**
**Problem**

Despite _reCaptcha_ we regularly face false registrations obviously made by robots.

**Solution**

I've added a new option into the plugin's settings **Minimal registration duration**. If set, registrations done faster than this limit are declined. I measure the time between displaying of the registration form and processing the the form. I think that It's not in human power to fill all the required fields in less than let's say 15 seconds.

After a fortnight testing we haven't registered a single false registration in our system. It's a simple but powerful solution.

### CODE REVIEW

**Comment by picman** [comment]
Any chance to accept this pull request?

**Comment by radiok** [comment]
Sorry for the delay, this is a bigger change than some of your previous requests, I have yet to fully review this.

**Comment by radiok** [comment]
Quick question, is there a reason you altered all the localization (*.mo/*.po) files?  That makes this a significantly more difficult commit to accept.

**Comment by radiok** [comment]
As is, the statement "Set to 0 to disable this check" was not entirely true.  Effectively it was true because the code would always "pass", but my expectation is that if disabled, we would not create the hidden field, or ever inspect it.  That was one significant change I made to your commit.  There was a bunch of minor nit picking with parenthesis and spacing which is important to me for consistency of the code base.  Something like PHP_EOL vs "\n" is very trivial but important for consistency.  PHP_EOL in fact is probably a better way, I never loved special characters for new lines, it's not clear to a more novice programmer... but that's neither here nor there.  I appreciate what you've done here, and I can see how this would improve your spam ratio.  I'd like to change the text describing the configuration a little bit, maybe make it more verbose and straight forward, but that's more polish than anything else.

**Pull request merged**
