### PR TITLE
Undefined variable error

### PR DESCRIPTION
**Pull request by picman**
I've tried to fix the "undefined variable" errors:
1. _$rpr_admin_menu_ by adding an annotation about  a variable included from another file.
2. _$terms_exist_ by adding a new class variable

### CODE REVIEW

**Comment by radiok** [comment]
@picman I updated your code changes to match the existing code.  I removed some type definitions, which is unfortunate, but, the code as is was written prior to PHP7 so I did not have access to type definitions at that time.  I do not want a change like this to be intermittent.  If you feel a desire, you can go through the code and basically convert the type comments to to type definition, however that's not a great use of yours, or my time, at this point.

**Comment by radiok** [comment]
@picman I reviewed the code a little more thoroughly, and I can see how the undefined variable condition could truly come to exist.  As such, I added an isset() call which should truly resolve the error.

**Comment by picman** [comment]
Thank you.

**Comment by radiok** [comment]
I have a couple questions for you if you have some time to answer them I'd appreciate it.

1. What version(s) of Wordpress are you using Register Plus Redux with?
2. Would you like to see Register Plus Redux back in the Wordpress plugin repository?

**Comment by picman** [comment]
1. 6.1.1., basically always the latest.
2. Yes, I would.

**Comment by radiok** [comment]
Fascinating, I expected more issues than the two you resolved.  I have not personally tested Redux since Wordpress 3.5, which from what I can tell was 26 releases ago!  I found a few different solutions to publish to Wordpress from GitHub, because I have ZERO desire to go back to SVN.  Also, thank you for your contributions!

**Pull request merged**
